# Generated by Django 3.2.21 on 2024-07-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mogc_partnerships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohortmembership',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
