# Generated by Django 3.2.21 on 2024-07-17 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mogc_partnerships', '0002_auto_20240703_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentrecord',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mogc_partnerships.partner'),
        ),
    ]
