name: Run quality checks
on: [push]
jobs:
  migrations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: pip install --user --upgrade nox
      - run: nox -s migrations
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: pip install --user --upgrade nox
      - run: nox -s lint
  sort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: pip install --user --upgrade nox
      - run: nox -s sort
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: pip install --user --upgrade nox
      - run: nox -s format
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
        django: ["3.2.0", "4.2.0", "5.0.0", "5.1.0"]
        exclude:
          - django: "5.0.0"
            python: "3.8"
          - django: "5.1.0"
            python: "3.8"
          - django: "5.0.0"
            python: "3.9"
          - django: "5.1.0"
            python: "3.9"
          - django: "3.2.0"
            python: "3.11"
          - django: "3.2.0"
            python: "3.12"
          - django: "3.2.0"
            python: "3.13"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - run: pip install --user --upgrade nox
      - run: nox -s "test(python='${{ matrix.python }}', django='${{ matrix.django }}')"
